source "https://rubygems.org"
group :jekyll_plugins do
  gem 'jekyll', "4.2"
  gem 'activesupport'
  gem 'jekyll-default-layout'
  gem 'jekyll-feed'
  gem 'jekyll-optional-front-matter'
  gem 'jekyll-relative-links'
  gem 'jekyll-include-cache'
  gem 'jekyll-redirect-from'
  gem 'kramdown'
  gem 'liquid'
  gem 'listen'
  gem 'nokogiri'
  gem 'rouge'
  gem 'rb-inotify'
  gem 'jekyll-redirect-from'
  gem 'jemoji'
  gem 'jekyll-mentions'
  gem 'liquid_pluralize'
  gem 'liquid_reading_time'
  gem 'jekyll-sitemap'
  gem 'jekyll-paginate'
  gem 'jekyll-gist'
  gem 'jekyll-figure'
  gem 'kramdown-parser-gfm'
end
